linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - gas
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - unconvert
    - gocyclo
    - goimports
    - megacheck
